### ISSUE TITLE
为什么我导入了静态xpth方法，没有selectElement方法。也没有attr方法。请问怎么获取标签的属性值？

### ISSUE THREAD

**Issue by hefan1990** [javaor/JanDanSpider#1]

**Comment by zhaohongxuan** [comment]
静态导入之后是有selectElement的方法的呀，我这边是正常的，你那边报什么错？![](http://ww1.sinaimg.cn/large/787edccfgw1fbka5d1yh9j20pn0e1dkd.jpg)
